In [2]:
import numpy as np

In [3]:
numbers = np.array([2, 3, 5, 7, 11])

In [4]:
type(numbers)

numpy.ndarray

In [5]:
numbers

array([ 2,  3,  5,  7, 11])

In [6]:
numbers[1]

3

In [7]:
y = np.int_([1,2,4])

In [8]:
y

array([1, 2, 4])

In [9]:
y.size

3

In [10]:
numbers.size

5

In [11]:
numbers.itemsize

4

In [12]:
for i in numbers.flat:
    print(i)

2
3
5
7
11


In [13]:
integers = np.array([[1, 2, 3], [4, 5, 6]])
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [14]:
integers.ndim

2

In [15]:
integers.shape

(2, 3)

In [16]:
y.ndim

1

In [17]:
y.shape

(3,)

In [19]:
for i in integers:
    print(i)

[1 2 3]
[4 5 6]


In [20]:
for i in integers.flat:
    print(i)

1
2
3
4
5
6


In [21]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [25]:
li = np.ones((20, 4), dtype=int)

In [26]:
li

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
li.ndim

2

In [32]:
li.shape

(20, 4)

In [33]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [34]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [35]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [47]:
import random

In [43]:
%timeit rolls_list = [random.randrange(1, 7) for i in range(0, 6_000_000)]

9.66 s ± 1.07 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [46]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

126 ms ± 32.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [48]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [49]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [52]:
numbers >= 13

array([False, False, False, False, False])

In [53]:
import pandas as pd

In [54]:
grades = pd.Series([87, 100, 94])

In [57]:
grades

0     87
1    100
2     94
dtype: int64

In [58]:
pd.Series(98.6, range(3))

0    98.6
1    98.6
2    98.6
dtype: float64

In [59]:
grades.count()

3

In [60]:
grades.min()

87

In [61]:
grades.std()

6.506407098647712

In [62]:
grades.describe()

count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64

In [63]:
grades = pd.Series([87, 100, 94], index=['Wally', 'Eva', 'Sam'])

In [68]:
grades

Wally     87
Eva      101
Sam       94
dtype: int64

In [67]:
grades = pd.Series({'Wally': 87, 'Eva': 101, 'Sam': 94})

In [69]:
grades['Eva']

101

In [70]:
grades.Wally

87

In [71]:
grades.values

array([ 87, 101,  94], dtype=int64)

In [72]:
hardware = pd.Series(['Hammer', 'Saw', 'Wrench'])

In [73]:
hardware.str.contains('a')

0     True
1     True
2    False
dtype: bool

In [74]:
hardware.str.upper()

0    HAMMER
1       SAW
2    WRENCH
dtype: object

In [75]:
grades_dict = {'Wally': [87, 96, 70], 'Eva': [100, 87, 90],'Sam': [94, 77, 90], 'Katie': [100, 81, 82], 'Bob': [83, 65, 85]}

In [98]:
grades = pd.DataFrame(grades_dict)

In [99]:
grades

Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [102]:
grades = pd.DataFrame(grades_dict, index=['Test1', 'Test2', 'Test3'])

In [97]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [90]:
grades['Eva']

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

In [83]:
grades.Sam

0    94
1    77
2    90
Name: Sam, dtype: int64

In [103]:
grades.loc['Test1']

Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

In [93]:
grades.iloc[1]

Wally    96
Eva      87
Sam      77
Katie    81
Bob      65
Name: Test2, dtype: int64

In [94]:
grades.loc[['Test1', 'Test3']]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [95]:
grades.iloc[[0, 2]]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [104]:
grades.loc['Test1':'Test2', ['Eva', 'Katie']]

Eva  Katie
Test1  100    100
Test2   87     81

In [105]:
grades.iloc[[0, 2], 0:3]

Wally  Eva  Sam
Test1     87  100   94
Test3     70   90   90

In [106]:
grades.iloc[[0, 2], 0:1]

Wally
Test1     87
Test3     70

In [109]:
grades[grades >= 80]

Wally  Eva   Sam  Katie   Bob
Test1   87.0  100  94.0    100  83.0
Test2   96.0   87   NaN     81   NaN
Test3    NaN   90  90.0     82  85.0

In [108]:
grades.iat[2, 0]

87

In [110]:
grades.iat[2, 0]

70

In [112]:
grades.iat[2, 1]

90

In [113]:
grades.describe()

Wally         Eva        Sam       Katie        Bob
count   3.000000    3.000000   3.000000    3.000000   3.000000
mean   84.333333   92.333333  87.000000   87.666667  77.666667
std    13.203535    6.806859   8.888194   10.692677  11.015141
min    70.000000   87.000000  77.000000   81.000000  65.000000
25%    78.500000   88.500000  83.500000   81.500000  74.000000
50%    87.000000   90.000000  90.000000   82.000000  83.000000
75%    91.500000   95.000000  92.000000   91.000000  84.000000
max    96.000000  100.000000  94.000000  100.000000  85.000000

In [114]:
grades.mean()

Wally    84.333333
Eva      92.333333
Sam      87.000000
Katie    87.666667
Bob      77.666667
dtype: float64

In [115]:
grades.sort_index(axis=1)

Bob  Eva  Katie  Sam  Wally
Test1   83  100    100   94     87
Test2   65   87     81   77     96
Test3   85   90     82   90     70

In [116]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [117]:
grades.sort_values(by='Test1', axis=1, ascending=False)

Eva  Katie  Sam  Wally  Bob
Test1  100    100   94     87   83
Test2   87     81   77     96   65
Test3   90     82   90     70   85

In [118]:
grades.loc['Test1'].sort_values(ascending=False)

Eva      100
Katie    100
Sam       94
Wally     87
Bob       83
Name: Test1, dtype: int64